version: '3.8'

services:
  redis:
    image: redis 

  db:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./database:/var/lib/postgresql/data 
    container_name: db-for-2.6

  example-backend:
    image: dockerized-example-backend
    build: ../../part1/1.13/example-backend 
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=root
      - REQUEST_ORIGIN=http://localhost/
    # ports:
    #   - 8080:8080
    container_name: example-backend 
    depends_on:
      - redis
      - db

  example-frontend:
    image: dockerized-example-frontend
    build: ../../part1/1.12/example-frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost/api/
    # ports:
    #   - 5000
    container_name: example-frontend
    depends_on:
      - example-backend

  nginx-proxy:
    image: nginx:1.19-alpine
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: nginx-proxy
    ports:
      - 80:80
    depends_on:
      - example-frontend