version: '3.8'

services:
  redis:
    image: redis 

  db:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./database:/var/lib/postgresql/data 
    container_name: db-for-2.6

  example-backend:
    image: dockerized-example-backend
    # build: ../../part1/1.13/example-backend 
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=root
    ports:
      - 8080:8080
    container_name: example-backend 

  example-frontend:
    image: dockerized-example-frontend
    # build: ../../part1/1.12/example-frontend
    ports:
      - 5000:5000
    container_name: example-frontend